<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>.NET Platform Architecture</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <style>
        body {
    padding: 60px 60px 60px 100px;
    font-family: PF Regal,Georgia,serif;
    font-size: 16pt;
    font-weight: 300;
}

strong {
    font-weight: 500;
}

p, li {
    margin: 0 0 14px;
    line-height: 32px;
    font-family: inherit;
}

ol, ul {
    padding-left: 35px;
    margin-top: 1.1rem;
    margin-bottom: 1.1rem;
}

ol li {
    padding-left: 10px;	
    font-family: inherit;
}

ul li {
    padding-left: 5px;	
    font-family: inherit;
}

code, .lang-csharp span, .lang-csharp pre {
    font-family: JB Mono, monospace !important;
}

.lang-csharp {
    padding: 4px 0px 14px 0px;
}


.lang-csharp > div {
    border-left-color: #eee;
    border-left-style: dotted;
    border-left-width: 3px;
    background-color: #f5faff !important;
    padding: 10px 10px 10px 25px;
}

code {
    font-size: 14px;
    border: gainsboro;
    border-width: 1px;
    border-style: solid;
    padding: 2px;
    color: darkslateblue;
}

.lang-csharp span, .lang-csharp pre {
    font-size: 13px;
    line-height: 20px;
}

p a, li a {
    text-decoration: none;
    color: inherit;
    box-shadow: inset 0 -1px #b88b59;
}

p img {
    width: 95%;
}

p (:has img) {
    text-align: center;
}

blockquote {
    background-color: lavenderblush;
    padding-left: 20px;
    border-left: 1px solid rgba(0,0,0,.08);
}

blockquote p {
    margin: 16px 0;
    padding: 12px 12px 13px;
    font-family: inherit;
}

blockquote p code {
    font-family: consolas, monospace;
    font-size: 17px;
    background-color: aliceblue;
    padding: 4px 6px;
}

h1, h2, h3, h4, h5, h6 {
    margin: 0;
    padding: 0;
    font-weight: 400;
    font-family: inherit;
}

h1 {
    font-size: 40px;
    font-family: PF Regal,Georgia,serif;
    font-weight: 300;
    margin: 40px 0 20px 0;
    border-bottom-style: ridge;
    padding-bottom: 10px;
}

h1 b {
    font-family: Proxima Nova,Arial,Helvetica Neue,sans-serif;
    font-weight: 700;
    font-size: 37px;
    line-height: 42px;
}

h2 {
    margin-top: 35px;
    margin-bottom: 10px;
    font-family: Proxima Nova,Arial,Helvetica Neue,sans-serif;
    font-size: 20px;
    font-weight: 700;
    line-height: 24px;
    border-bottom-color: grey;
    border-bottom-style: solid;
    padding-bottom: 5px;
}

h3 {
    margin: 30px 0 10px 0;
    font-size: 17pt;
    font-weight: 500;
}

h4 {
    margin: 20px 0 10px 0;
    font-size: 16pt;
    font-weight: 500;
    font-style: italic;
}

/* Fonts 

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-RegularA.eot');
    src: local('../../../res/fonts/PFRegalTextPro-RegularA'),
        url('../../../res/fonts/PFRegalTextPro-RegularA.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-RegularA.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-RegularA.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-Bold.eot');
    src: local('../../../res/fonts/PFRegalTextPro-Bold'),
        url('../../../res/fonts/PFRegalTextPro-Bold.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-Bold.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
}
*/
@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-Medium.eot');
    src: local('../../../res/fonts/PFRegalTextPro-Medium'),
        url('../../../res/fonts/PFRegalTextPro-Medium.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-Medium.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-Medium.ttf') format('truetype');
    font-weight: 500;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-BlackItalic.eot');
    src: local('../../../res/fonts/PFRegalTextPro-BlackItalic'),
        url('../../../res/fonts/PFRegalTextPro-BlackItalic.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-BlackItalic.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-BlackItalic.ttf') format('truetype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-Black.eot');
    src: local('../../../res/fonts/PFRegalTextPro-Black'),
        url('../../../res/fonts/PFRegalTextPro-Black.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-Black.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-Black.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal UBlack';
    src: url('../../../res/fonts/PFRegalTextPro-UBlack.eot');
    src: local('../../../res/fonts/PFRegalTextPro-UBlack'),
        url('../../../res/fonts/PFRegalTextPro-UBlack.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-UBlack.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-UBlack.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-MediumItalic.eot');
    src: local('../../../res/fonts/PFRegalTextPro-MediumItalic'),
        url('../../../res/fonts/PFRegalTextPro-MediumItalic.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-MediumItalic.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-MediumItalic.ttf') format('truetype');
    font-weight: 500;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-UBlackItalic.eot');
    src: local('../../../res/fonts/PFRegalTextPro-UBlackItalic'),
        url('../../../res/fonts/PFRegalTextPro-UBlackItalic.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-UBlackItalic.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-UBlackItalic.ttf') format('truetype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-RegularAItalic.eot');
    src: local('../../../res/fonts/PFRegalTextPro-RegularAItalic'),
        url('../../../res/fonts/PFRegalTextPro-RegularAItalic.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-RegularAItalic.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-RegularAItalic.ttf') format('truetype');
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-BoldItalic.eot');
    src: local('../../../res/fonts/PFRegalTextPro-BoldItalic'),
        url('../../../res/fonts/PFRegalTextPro-BoldItalic.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-BoldItalic.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-BoldItalic.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
}

/*  Regular B */
@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-RegularBItalic.eot');
    src: local('../../../res/fonts/PFRegalTextPro-RegularBItalic'),
        url('../../../res/fonts/PFRegalTextPro-RegularBItalic.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-RegularBItalic.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-RegularBItalic.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../res/fonts/PFRegalTextPro-RegularB.eot');
    src: local('../../../res/fonts/PFRegalTextPro-RegularB'),
        url('../../../res/fonts/PFRegalTextPro-RegularB.woff2') format('woff2'),
        url('../../../res/fonts/PFRegalTextPro-RegularB.woff') format('woff'),
        url('../../../res/fonts/PFRegalTextPro-RegularB.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}                
    </style>

<div style="margin:auto; width:100%;">
<div style="width:1000px;">
    <h2 id="section">События об исключительных ситуациях</h2>
<blockquote>
<p><a href="https://github.com/sidristij/dotnetbook/issues/51">Ссылка на обсуждение</a></p>
</blockquote>
<p>В общем случае мы не всегда знаем о тех исключениях, которые произойдут в наших программах потому что практически всегда мы используем что-то, что написано другими людьми и что находится в других подсистемах и библиотеках. Мало того что возможны самые разные ситуации в вашем собственном коде, в коде других библиотек, так ещё и существует множество проблем, связанных с исполнением кода в изолированных доменах. И как раз в этом случае было бы крайне полезно уметь получать данные о работе изолированного кода. Ведь вполне реальной может быть ситуация, когда сторонний код перехватывает все без исключения ошибки, заглушив их <code>fault</code> блоком:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
    <span style="color:Blue;">try</span> {
        <span style="color:Green;">// ...</span>
    } <span style="color:Blue;">catch</span> {
        <span style="color:Green;">// do nothing, just to make code call safer</span>
    }
</pre></div>
</div>
<p>В такой ситуации может оказаться, что выполнение кода уже не так безопасно как выглядит, но сообщений о том, что произошли какие-то проблемы мы не имеем. Второй вариант - когда приложение глушит некоторое, пусть даже легальное, исключение. А результат - следующее исключение в случайном месте вызовет падение приложения в некотором будущем от случайной, казалось бы, ошибки. Тут хотелось бы иметь представление, какая была предыстория этой ошибки. Каков ход событий привёл к такой ситуации. И один из способов сделать это возможным - использовать дополнительные события, которые относятся к исключительным ситуациям: <code>AppDomain.FirstChanceException</code> и <code>AppDomain.UnhandledException</code>.</p>
<p>Фактически, когда вы &quot;бросаете исключение&quot;, то вызывается обычный метод некоторой внутренней подсистемы <code>Throw</code>, который внутри себя проделывает следующие операции:</p>
<ul>
<li>Вызывает <code>AppDomain.FirstChanceException</code></li>
<li>Ищет в цепочке обработчиков подходящий по фильтрам</li>
<li>Вызывает обработчик, предварительно откатив стек на нужный кадр</li>
<li>Если обработчик найден не был, вызывается <code>AppDomain.UnhandledException</code>, обрушивая поток, в котором произошло исключение.</li>
</ul>
<p>Сразу следует оговориться, ответив на мучающий многие умы вопрос: есть ли возможность как-то отменить исключение, возникшее в неконтролируемом коде, который исполняется в изолированном домене, не обрушивая тем самым поток, в котором это исключение было выброшено? Ответ лаконичен и прост: нет. Если исключение не перехватывается на всем диапазоне вызванных методов, оно не может быть обработано в принципе. Иначе возникает странная ситуация: если мы при помощи <code>AppDomain.FirstChanceException</code> обрабатываем (некий синтетический <code>catch</code>) исключение, то на какой кадр должен откатиться стек потока? Как это задать в рамках правил .NET CLR? Никак. Это просто не возможно. Единственное что мы можем сделать - запротоколировать полученную информацию для будущих исследований.</p>
<p>Второе, о чем следует рассказать &quot;на берегу&quot; - это почему эти события введены не у <code>Thread</code>, а у <code>AppDomain</code>. Ведь если следовать логике, исключения возникают где? В потоке исполнения команд. Т.е. фактически у <code>Thread</code>. Так почему же проблемы возникают у домена? Ответ очень прост: для каких ситуаций создавались <code>AppDomain.FirstChanceException</code> и <code>AppDomain.UnhandledException</code>? Помимо всего прочего - для создания песочниц для плагинов. Т.е. для ситуаций, когда есть некий <code>AppDomain</code>, который настроен на PartialTrust. Внутри этого AppDomain может происходить что угодно: там в любой момент могут создаваться потоки, или использоваться уже существующие из ThreadPool. Тогда получается что мы, будучи находясь снаружи от этого процесса (не мы писали тот код) не можем никак подписаться на события внутренних потоков. Просто потому что мы понятия не имеем что там за потоки были созданы. Зато мы гарантированно имеем <code>AppDomain</code>, который организует песочницу и ссылка на который у нас есть.</p>
<p>Итак, по факту нам предоставляется два краевых события: что-то произошло, чего не предполагалось (<code>FirstChanceExecption</code>) и &quot;все плохо&quot;, никто не обработал исключительную ситуацию: она оказалась не предусмотренной. А потому поток исполнения команд не имеет смысла и он (<code>Thread</code>) будет отгружен.</p>
<p>Что можно получить, имея данные события и почему плохо что разработчики обходят эти события стороной?</p>
<h3 id="appdomain.firstchanceexception">AppDomain.FirstChanceException</h3>
<p>Это событие по своей сути носит чисто информационный характер и не может быть &quot;обработано&quot;. Его задача - уведомить вас, что в рамках данного домена произошло исключение, и оно после обработки события начнёт обрабатываться кодом приложения. Его исполнение несёт за собой пару особенностей, о которых необходимо помнить во время проектирования обработчика.</p>
<p>Но давайте для начала посмотрим на простой синтетический пример его обработки:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">void</span> Main()
{
    <span style="color:Blue;">var</span> counter = 0;

    AppDomain.CurrentDomain.FirstChanceException += (_, args) =&gt; {
        Console.WriteLine(args.Exception.Message);
        <span style="color:Blue;">if</span>(++counter == 1) {
            <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> ArgumentOutOfRangeException();
        }
    };

    <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> Exception(<span style="color:#A31515;">&quot;Hello!&quot;</span>);
}
</pre></div>
</div>
<p>Чем примечателен данный код? Где бы некий код ни сгенерировал бы исключение первое что произойдёт - это его логирование в консоль. Т.е. даже если вы забудете или не сможете предусмотреть обработку некоторого типа исключения оно все равно появится в журнале событий, которое вы организуете. Второе - несколько странное условие выброса внутреннего исключения. Все дело в том, что внутри обработчика <code>FirstChanceException</code> вы не можете просто взять и бросить ещё одно исключение. Скорее даже так: внутри обработчика FirstChanceException вы <em>не имеете возможности</em> бросить хоть какое-либо исключение. Если вы так сделаете, возможны два варианта событий. При первом, если бы не было условия <code>if(++counter == 1)</code>, мы бы получили бесконечный выброс <code>FirstChanceException</code> для все новых и новых <code>ArgumentOutOfRangeException</code>. А что это значит? Это значит, что на определённом этапе мы бы получили <code>StackOverflowException</code>: <code>throw new Exception(&quot;Hello!&quot;)</code> вызывает CLR метод Throw, который вызывает <code>FirstChanceException</code>, который вызывает <code>Throw</code> уже для <code>ArgumentOutOfRangeException</code> и далее - по рекурсии. Второй вариант: мы защитились по глубине рекурсии при помощи условия по <code>counter</code>. Т.е. в данном случае мы бросаем исключение только один раз. Результат более чем неожиданный: мы получим исключительную ситуацию, которая фактически отрабатывает внутри инструкции <code>Throw</code>. А что подходит более всего для данного типа ошибки? Согласно ECMA-335 если инструкция была введена в исключительное положение, должно быть выброшено <code>ExecutionEngineException</code>! А эту исключительную ситуацию мы обработать никак не в состоянии. Она приводит к полному вылету из приложения. Какие же варианты безопасной обработки у нас есть?</p>
<p>Первое, что приходит в голову - это выставить <code>try-catch</code> блок на весь код обработчика <code>FirstChanceException</code>:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">void</span> Main()
{
    <span style="color:Blue;">var</span> fceStarted = <span style="color:Blue;">false</span>;
    <span style="color:Blue;">var</span> sync = <span style="color:Blue;">new</span> <span style="color:Blue;">object</span>();
    EventHandler&lt;FirstChanceExceptionEventArgs&gt; handler;
    handler = <span style="color:Blue;">new</span> EventHandler&lt;FirstChanceExceptionEventArgs&gt;((_, args) =&gt;
    {
        <span style="color:Blue;">lock</span> (sync)
        {
            <span style="color:Blue;">if</span> (fceStarted)
            {
                <span style="color:Green;">// Этот код по сути - заглушка, призванная уведомить что исключение по своей сути - родилось не в основном коде приложения, </span>
                <span style="color:Green;">// а в try блоке ниже.</span>
                Console.WriteLine($<span style="color:#A31515;">&quot;FirstChanceException inside FirstChanceException ({args.Exception.GetType().FullName})&quot;</span>);
                <span style="color:Blue;">return</span>;
            }
            fceStarted = <span style="color:Blue;">true</span>;

            <span style="color:Blue;">try</span>
            {
                <span style="color:Green;">// не безопасное логгирование куда угодно. Например, в БД</span>
                Console.WriteLine(args.Exception.Message);
                <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> ArgumentOutOfRangeException();
            }
            <span style="color:Blue;">catch</span> (Exception exception)
            {
                <span style="color:Green;">// это логгирование должно быть максимально безопасным</span>
                Console.WriteLine(<span style="color:#A31515;">&quot;Success&quot;</span>);
            }
            <span style="color:Blue;">finally</span>
            {
                fceStarted = <span style="color:Blue;">false</span>;
            }
        }
    });
    AppDomain.CurrentDomain.FirstChanceException += handler;

    <span style="color:Blue;">try</span>
    {
        <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> Exception(<span style="color:#A31515;">&quot;Hello!&quot;</span>);
    } <span style="color:Blue;">finally</span> {
        AppDomain.CurrentDomain.FirstChanceException -= handler;
    }
}

OUTPUT:

Hello!
Specified argument was <span style="color:Blue;">out</span> of the range of valid values.
FirstChanceException inside FirstChanceException (System.ArgumentOutOfRangeException)
Success

!Exception: Hello!
</pre></div>
</div>
<p>Т.е. с одной стороны у нас есть код обработки события <code>FirstChanceException</code>, а с другой - дополнительный код обработки исключений в самом <code>FirstChanceException</code>. Однако методики логгирования обеих ситуаций должны отличаться. Если логирование обработки события может идти как угодно, то обработка ошибки логики обработки <code>FirstChanceException</code> должно идти без исключительных ситуаций в принципе. Второе, что вы наверняка заметили - это синхронизация между потоками. Тут может возникнуть вопрос: зачем она тут, если любое исключение рождено в каком-либо потоке, а значит <code>FirstChanceException</code> по идее должен быть потокобезопасным. Однако, все не так жизнерадостно. <code>FirstChanceException</code> у нас возникает у AppDomain. А это значит, что он возникает для любого потока, стартованного в определённом домене. Т.е. если у нас есть домен, внутри которого стартовано несколько потоков, то <code>FirstChanceException</code> могут идти в параллель. А это значит, что нам необходимо как-то защитить себя синхронизацией: например при помощи <code>lock</code>.</p>
<p>Второй способ - попробовать увести обработку в соседний поток, принадлежащий другому домену приложений. Однако тут стоит оговориться, что при такой реализации мы должны построить выделенный домен именно под эту задачу чтобы не получилось так, что этот домен могут положить другие потоки, которые являются рабочими:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">static</span> <span style="color:Blue;">void</span>  Main()
{
    <span style="color:Blue;">using</span> (ApplicationLogger.Go(AppDomain.CurrentDomain))
    {
        <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> Exception(<span style="color:#A31515;">&quot;Hello!&quot;</span>);
    }
}

<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> ApplicationLogger : MarshalByRefObject
{
    ConcurrentQueue&lt;Exception&gt; queue = <span style="color:Blue;">new</span> ConcurrentQueue&lt;Exception&gt;();
    CancellationTokenSource cancellation;
    ManualResetEvent @<span style="color:Blue;">event</span>;

    <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> LogFCE(Exception message)
    {
        queue.Enqueue(message);
    }

    <span style="color:Blue;">private</span> <span style="color:Blue;">void</span> StartThread()
    {
        cancellation = <span style="color:Blue;">new</span> CancellationTokenSource();
        @<span style="color:Blue;">event</span> = <span style="color:Blue;">new</span> ManualResetEvent(<span style="color:Blue;">false</span>);
        <span style="color:Blue;">var</span> thread = <span style="color:Blue;">new</span> Thread(() =&gt;
        {
            <span style="color:Blue;">while</span> (!cancellation.IsCancellationRequested)
            {
                <span style="color:Blue;">if</span> (queue.TryDequeue(<span style="color:Blue;">out</span> <span style="color:Blue;">var</span> exception))
                {
                    Console.WriteLine(exception.Message);
                }
                Thread.Yield();
            }
            @<span style="color:Blue;">event</span>.Set();
        });
        thread.Start();
    }

    <span style="color:Blue;">private</span> <span style="color:Blue;">void</span> StopAndWait()
    {
        cancellation.Cancel();
        @<span style="color:Blue;">event</span>.WaitOne();
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">static</span> IDisposable Go(AppDomain observable)
    {
        <span style="color:Blue;">var</span> dom = AppDomain.CreateDomain(<span style="color:#A31515;">&quot;ApplicationLogger&quot;</span>, <span style="color:Blue;">null</span>, <span style="color:Blue;">new</span> AppDomainSetup
        {
            ApplicationBase = AppDomain.CurrentDomain.BaseDirectory,
        });

        <span style="color:Blue;">var</span> proxy = (ApplicationLogger)dom.CreateInstanceAndUnwrap(<span style="color:Blue;">typeof</span>(ApplicationLogger).Assembly.FullName, <span style="color:Blue;">typeof</span>(ApplicationLogger).FullName);
        proxy.StartThread();

        <span style="color:Blue;">var</span> subscription = <span style="color:Blue;">new</span> EventHandler&lt;FirstChanceExceptionEventArgs&gt;((_, args) =&gt;
        {
            proxy.LogFCE(args.Exception);
        });
        observable.FirstChanceException += subscription;

        <span style="color:Blue;">return</span> <span style="color:Blue;">new</span> Subscription(() =&gt; {
            observable.FirstChanceException -= subscription;
            proxy.StopAndWait();
        });
    }

    <span style="color:Blue;">private</span> <span style="color:Blue;">class</span> Subscription : IDisposable
    {
        Action act;
        <span style="color:Blue;">public</span> Subscription (Action act) {
            <span style="color:Blue;">this</span>.act = act;
        }
        <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> Dispose()
        {
            act();
        }
    }
}
</pre></div>
</div>
<p>В данном случае обработка <code>FirstChanceException</code> происходит максимально безопасно: в соседнем потоке, принадлежащем соседнему домену. Ошибки обработки сообщения при этом не могут обрушить рабочие потоки приложения. Плюс отдельно можно послушать UnhandledException домена логирования сообщений: фатальные ошибки при логировании не обрушат все приложение.</p>
<h3 id="appdomain.unhandledexception">AppDomain.UnhandledException</h3>
<p>Второе сообщение, которое мы можем перехватить и которое касается обработки исключительных ситуаций - это <code>AppDomain.UnhandledException</code>. Это сообщение - очень плохая новость для нас поскольку обозначает что не нашлось никого кто смог бы найти способ обработки возникшей ошибки в некотором потоке. Также, если произошла такая ситуация, все что мы можем сделать - это &quot;разгрести&quot; последствия такой ошибки. Т.е. каким-либо образом зачистить ресурсы, принадлежащие только этому потоку, если таковые создавались. Однако, ещё более лучшая ситуация - обрабатывать исключения, находясь в &quot;корне&quot; потоков не заваливая поток. Т.е. по сути ставить <code>try-catch</code>. Давайте попробуем рассмотреть целесообразность такого поведения.</p>
<p>Пусть мы имеем библиотеку, которой необходимо создавать потоки и осуществлять какую-то логику в этих потоках. Мы, как пользователи этой библиотеки интересуемся только гарантией вызовов API а также получением сообщений об ошибках. Если библиотека будет рушить потоки не нотифицируя об этом, нам это мало чем может помочь. Мало того обрушение потока приведёт к сообщению <code>AppDomain.UnhandledException</code>, в котором нет информации о том, какой конкретно поток лёг на бок. Если же речь идёт о нашем коде, обрушивающийся поток нам тоже вряд-ли будет полезным. Во всяком случае необходимости в этом я не встречал. Наша задача - обработать ошибки правильно, отдать информацию об их возникновении в журнал ошибок и корректно завершить работу потока. Т.е. по сути, обернуть метод, с которого стартует поток в <code>try-catch</code>:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
    ThreadPool.QueueUserWorkitem(_ =&gt; {
        <span style="color:Blue;">using</span>(Disposables aggregator = ...){
            <span style="color:Blue;">try</span> {
                <span style="color:Green;">// do work here, plus:</span>
                aggregator.Add(subscriptions);
                aggregator.Add(dependantResources);
            } <span style="color:Blue;">catch</span> (Exception ex)
            {
                logger.Error(ex, <span style="color:#A31515;">&quot;Unhandled exception&quot;</span>);
            }
        }
    });
</pre></div>
</div>
<p>В такой схеме мы получим то, что надо: с одной стороны мы не обрушим поток. С другой - корректно очистим локальные ресурсы, если они были созданы. Ну и в довесок - организуем журналирование полученной ошибки. Но постойте, скажете вы. Как-то вы лихо соскочили с вопроса события <code>AppDomain.UnhandledException</code>. Неужели оно совсем не нужно? Нужно. Но только для того чтобы сообщить, что мы забыли обернуть какие-то потоки в <code>try-catch</code> со всей необходимой логикой. Именно со всей: с логированием и очисткой ресурсов. Иначе это будет совершенно не правильно: брать и гасить все исключения, как будто их и не было вовсе.</p>

</div>
</div>
</body>
</html>