<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>.NET Platform Architecture</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <style>
        body {
    padding: 60px 60px 60px 100px;
    font-family: PF Regal,Georgia,serif;
    font-size: 16pt;
    font-weight: 300;
}

strong {
    font-weight: 500;
}

p, li {
    margin: 0 0 14px;
    line-height: 32px;
    font-family: inherit;
}

ol, ul {
    padding-left: 35px;
    margin-top: 1.1rem;
    margin-bottom: 1.1rem;
}

ol li {
    padding-left: 10px;	
    font-family: inherit;
}

ul li {
    padding-left: 5px;	
    font-family: inherit;
}

code, .lang-csharp span, .lang-csharp pre {
    font-family: JB Mono, monospace !important;
}

.lang-csharp {
    padding: 4px 0px 14px 0px;
}


.lang-csharp > div {
    border-left-color: #eee;
    border-left-style: dotted;
    border-left-width: 3px;
    background-color: #f5faff !important;
    padding: 10px 10px 10px 25px;
}

code {
    font-size: 14px;
    border: gainsboro;
    border-width: 1px;
    border-style: solid;
    padding: 2px;
    color: darkslateblue;
}

.lang-csharp span, .lang-csharp pre {
    font-size: 13px;
    line-height: 20px;
}

p a, li a {
    text-decoration: none;
    color: inherit;
    box-shadow: inset 0 -1px #b88b59;
}

p img {
    width: 95%;
}

p (:has img) {
    text-align: center;
}

blockquote {
    background-color: lavenderblush;
    padding-left: 20px;
    border-left: 1px solid rgba(0,0,0,.08);
}

blockquote p {
    margin: 16px 0;
    padding: 12px 12px 13px;
    font-family: inherit;
}

blockquote p code {
    font-family: consolas, monospace;
    font-size: 17px;
    background-color: aliceblue;
    padding: 4px 6px;
}

h1, h2, h3, h4, h5, h6 {
    margin: 0;
    padding: 0;
    font-weight: 400;
    font-family: inherit;
}

h1 {
    font-size: 40px;
    font-family: PF Regal,Georgia,serif;
    font-weight: 300;
    margin: 40px 0 20px 0;
    border-bottom-style: ridge;
    padding-bottom: 10px;
}

h1 b {
    font-family: Proxima Nova,Arial,Helvetica Neue,sans-serif;
    font-weight: 700;
    font-size: 37px;
    line-height: 42px;
}

h2 {
    margin-top: 35px;
    margin-bottom: 10px;
    font-family: Proxima Nova,Arial,Helvetica Neue,sans-serif;
    font-size: 20px;
    font-weight: 700;
    line-height: 24px;
    border-bottom-color: grey;
    border-bottom-style: solid;
    padding-bottom: 5px;
}

h3 {
    margin: 30px 0 10px 0;
    font-size: 17pt;
    font-weight: 500;
}

h4 {
    margin: 20px 0 10px 0;
    font-size: 16pt;
    font-weight: 500;
    font-style: italic;
}

/* Fonts 

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-RegularA.eot');
    src: local('../../res/fonts/PFRegalTextPro-RegularA'),
        url('../../res/fonts/PFRegalTextPro-RegularA.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-RegularA.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-RegularA.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-Bold.eot');
    src: local('../../res/fonts/PFRegalTextPro-Bold'),
        url('../../res/fonts/PFRegalTextPro-Bold.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-Bold.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
}
*/
@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-Medium.eot');
    src: local('../../res/fonts/PFRegalTextPro-Medium'),
        url('../../res/fonts/PFRegalTextPro-Medium.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-Medium.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-Medium.ttf') format('truetype');
    font-weight: 500;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-BlackItalic.eot');
    src: local('../../res/fonts/PFRegalTextPro-BlackItalic'),
        url('../../res/fonts/PFRegalTextPro-BlackItalic.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-BlackItalic.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-BlackItalic.ttf') format('truetype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-Black.eot');
    src: local('../../res/fonts/PFRegalTextPro-Black'),
        url('../../res/fonts/PFRegalTextPro-Black.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-Black.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-Black.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal UBlack';
    src: url('../../res/fonts/PFRegalTextPro-UBlack.eot');
    src: local('../../res/fonts/PFRegalTextPro-UBlack'),
        url('../../res/fonts/PFRegalTextPro-UBlack.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-UBlack.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-UBlack.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-MediumItalic.eot');
    src: local('../../res/fonts/PFRegalTextPro-MediumItalic'),
        url('../../res/fonts/PFRegalTextPro-MediumItalic.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-MediumItalic.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-MediumItalic.ttf') format('truetype');
    font-weight: 500;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-UBlackItalic.eot');
    src: local('../../res/fonts/PFRegalTextPro-UBlackItalic'),
        url('../../res/fonts/PFRegalTextPro-UBlackItalic.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-UBlackItalic.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-UBlackItalic.ttf') format('truetype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-RegularAItalic.eot');
    src: local('../../res/fonts/PFRegalTextPro-RegularAItalic'),
        url('../../res/fonts/PFRegalTextPro-RegularAItalic.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-RegularAItalic.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-RegularAItalic.ttf') format('truetype');
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-BoldItalic.eot');
    src: local('../../res/fonts/PFRegalTextPro-BoldItalic'),
        url('../../res/fonts/PFRegalTextPro-BoldItalic.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-BoldItalic.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-BoldItalic.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
}

/*  Regular B */
@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-RegularBItalic.eot');
    src: local('../../res/fonts/PFRegalTextPro-RegularBItalic'),
        url('../../res/fonts/PFRegalTextPro-RegularBItalic.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-RegularBItalic.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-RegularBItalic.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../res/fonts/PFRegalTextPro-RegularB.eot');
    src: local('../../res/fonts/PFRegalTextPro-RegularB'),
        url('../../res/fonts/PFRegalTextPro-RegularB.woff2') format('woff2'),
        url('../../res/fonts/PFRegalTextPro-RegularB.woff') format('woff'),
        url('../../res/fonts/PFRegalTextPro-RegularB.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}                
    </style>

<div style="margin:auto; width:100%;">
<div style="width:1000px;">
    <h2 id="events-that-indicate-exceptional-situations">Events that indicate exceptional situations</h2>
<blockquote>
<p><a href="https://github.com/sidristij/dotnetbook/issues/51">A link to the discussion</a></p>
</blockquote>
<p>In general, we don’t always know about those exceptions that can happen in our programs because we almost always use somebody else’s code, something that is in other subsystems or libraries. Not only are different situations possible in your code or in the code of other libraries, but there are a lot of problems with running code in isolated domains. In this case, it would be useful to get information about the running isolated code  because the situation when third-party code catches all exceptions by addressing them with a <code>fault</code> block can be quite real:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
    <span style="color:Blue;">try</span> {
        <span style="color:Green;">// ...</span>
    } <span style="color:Blue;">catch</span> {
        <span style="color:Green;">// just to make code call safer</span>
    }
</pre></div>
</div>
<p>In this case, the execution of code may seem safer as it actually is, but we won’t get any messages about problems. The second case is when an application suppresses an exception, even a legal one. As a result, the next exception in a random place will cause the application to break down because of a seemingly accidental error. In this case, we would prefer to know what happened prior to this error. What chain of events caused such an outcome? To make this knowledge possible you may choose to employ additional events that belong to exceptional situations: <code>AppDomain.FirstChanceException</code> and <code>AppDomain.UnhandledException</code>.</p>
<p>In fact, when you <em>&quot;throw an exception&quot;</em>, you call an ordinary method of the <code>throw</code> subsystem. This method performs several internal operations:</p>
<ul>
<li>calls <code>AppDomain.FirstChanceException</code>;</li>
<li>looks through the chain of handlers to find one with relevant filters;</li>
<li>goes back to a necessary frame in stack and calls the handler;</li>
<li>if the handler was not found, calls <code>AppDomain.UnhandledException</code> and terminates the thread where the exception was thrown.</li>
</ul>
<p>You may wonder if you can cancel the exception in uncontrolled code which runs in an isolated domain without terminating the thread where this exception was thrown. The answer is NO.</p>
<p>If an exception was not caught throughout the whole range of called methods it can’t be handled at all. Otherwise, there is a strange situation: if we use <code>AppDomain.FirstChanceException</code> to process (with some synthetic <code>catch</code>) an exception, which frame should the stack go back to? How should we set it up within the rules of <code>.NET</code> CLR? In no way. It’s impossible. The only thing we can do is to record this data for future research.</p>
<p>Another thing we should mention at &quot;the very beginning” is why <code>thread</code> and not <code>AppDomain</code> has these events. It is because exceptions logically appear in an execution thread. That means <code>thread</code> in fact. So, why does a domain have problems? The answer is simple: what are the situations <code>AppDomain.FirstChanceException</code> and <code>AppDomain.UnhandledException</code> used for? Above all, they are used to create sandboxes for plug-ins, i.e. situations where there is some <code>AppDomain</code> which is set for PartialTrust. All kinds of things can happen in this <code>AppDomain</code>: new threads can be created at any moment or those already existing in <code>ThreadPool</code> can be used. Thus, we, being outside this process (as we didn’t write this code), can’t subscribe to events of these internal threads — we just don’t know what threads were created there. But we definitely have the <code>AppDomain</code> which we have a link to and which creates a sandbox for us.</p>
<p>So, in fact, we have two boundary states: something unexpected happened (<code>FirstChanceException</code>) and &quot;things are bad&quot;, the exception was unexpected and nobody handled it. That’s why further thread execution makes no sense and the <code>thread</code> will be unloaded.</p>
<p>What can we get if we have these events and why is it bad if developers ignore them.</p>
<h3 id="appdomain.firstchanceexception">AppDomain.FirstChanceException</h3>
<p>This event is purely informational and can’t be handled. Its task is to notify us about an exception that happened within this domain and will be processed by the application code after processing the event. Its execution has several features we should be aware of when designing a handler.</p>
<p>However, let’s first look at a simple synthetic example of exception handling:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">void</span> Main()
{
    <span style="color:Blue;">var</span> counter = 0;

    AppDomain.CurrentDomain.FirstChanceException += (_, args) =&gt; {

        Console.WriteLine(args.Exception.Message);

        <span style="color:Blue;">if</span>(++counter == 1) {
            <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> ArgumentOutOfRangeException();
        }
    };

    <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> Exception(<span style="color:#A31515;">&quot;Hello!&quot;</span>);
}

</pre></div>
</div>
<p>What is in this code?</p>
<p>Firstly, no matter where an exception is generated, it will be logged in a console first. I mean even if you forget or can’t implement the handling of some type of exception it will anyway appear in a log that you arrange.</p>
<p>Secontly, we see a somewhat strange condition for throwing an internal exception. It is because you can’t just throw another exception inside a <code>FirstChanceException</code> handler. Or, it’s better to say you <em>don’t have an opportunity</em> to throw an exception inside <code>FirstChanceException</code>. If you do this, it may have two possible outcomes.</p>
<p>First, if we didn’t have the <code>if(++counter == 1)</code> condition, we would get infinite <code>FirstChanceException</code> for all new <code>ArgumentOutOfRangeException</code>. What does it mean? It means that at some point we would get <code>StackOverflowException</code>: <code>throw new Exception(&quot;Hello!&quot;)</code> calls the <code>Throw</code> CLR method that calls <code>FirstChanceException</code> which calls <code>Throw</code> for <code>ArgumentOutOfRangeException</code> already and so on based on recursion. The second variant involves protecting ourselves in terms of recursion depth using <code>counter</code> condition. In this case, we throw an exception only once. The result is unexpected as we get an exceptional situation which in fact occurs inside a <code>throw</code> instruction.</p>
<p>What does fit best for such an error type? ECMA-335 says that if an instruction came to an unexpected state, <code>ExecutionEngineException</code> should be thrown. This is an exception that we can’t handle. It leads to application termination. What variants of safe handling do we have?</p>
<p>The first that comes to mind is to secure the whole <code>FirstChanceException</code> handler code by a <code>try-catch</code> block:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">void</span> Main()
{
    <span style="color:Blue;">var</span> fceStarted = <span style="color:Blue;">false</span>;
    <span style="color:Blue;">var</span> sync = <span style="color:Blue;">new</span> <span style="color:Blue;">object</span>();

    EventHandler&lt;FirstChanceExceptionEventArgs&gt; handler;
    handler = <span style="color:Blue;">new</span> EventHandler&lt;FirstChanceExceptionEventArgs&gt;((_, args) =&gt;
    {
        <span style="color:Blue;">lock</span> (sync)
        {
            <span style="color:Blue;">if</span> (fceStarted)
            {
                <span style="color:Green;">// This code is in fact a stub to notify that an exception comes not from the main code of an application </span>
                <span style="color:Green;">// but from the `try` section below.</span>
                Console.WriteLine($<span style="color:#A31515;">&quot;FirstChanceException inside FirstChanceException ({args.Exception.GetType().FullName})&quot;</span>);
                <span style="color:Blue;">return</span>;
            }
            fceStarted = <span style="color:Blue;">true</span>;

            <span style="color:Blue;">try</span>
            {
                <span style="color:Green;">// unsafe logging to some place,  e. g. to a database</span>
                Console.WriteLine(args.Exception.Message);
                <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> ArgumentOutOfRangeException();
            }
            <span style="color:Blue;">catch</span> (Exception exception)
            {
                <span style="color:Green;">// this logging must be absolutely safe</span>
                Console.WriteLine(<span style="color:#A31515;">&quot;Success&quot;</span>);
            }
            <span style="color:Blue;">finally</span>
            {
                fceStarted = <span style="color:Blue;">false</span>;
            }
        }
    });

    AppDomain.CurrentDomain.FirstChanceException += handler;

    <span style="color:Blue;">try</span>
    {
        <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> Exception(<span style="color:#A31515;">&quot;Hello!&quot;</span>);
    } <span style="color:Blue;">finally</span> {
        AppDomain.CurrentDomain.FirstChanceException -= handler;
    }
}

OUTPUT:

Hello!
Specified argument was <span style="color:Blue;">out</span> of the range of valid values.
FirstChanceException inside FirstChanceException (System.ArgumentOutOfRangeException)
Success

!Exception: Hello!
</pre></div>
</div>
<p>Thus, on the one hand, we have a code to handle a <code>FirstChanceException</code> event and on the other hand, we have an additional code to handle exceptions in <code>FirstChanceException</code> itself.</p>
<p>However, approaches to log both scenarios should be different. If event processing can be logged in any possible way, the handling of <code>FirstChanceException</code> logic error should be done without any exceptions. The second thing, which you probably noticed, is the synchronization among threads. You may ask why it should be here if any exception appears in some thread which means that <code>FirstChanceException</code> is thread-safe in theory.</p>
<p>Don’t be so optimistic. <code>FirstChanceException</code> happens in <code>AppDomain</code>.  It means it impacts any thread started in a particular domain. Thus, if we have a domain with several running threads, then <code>FirstChanceException</code> can run in parallel. It means that we should protect our thread by synchronization, e.g. using <code>lock</code>.</p>
<p>Another way is to transfer exception handling to an adjacent thread, belonging to another application domain. However, in this case we should build a domain, dedicated for this task so that other worker threads wouldn’t bring this domain down.</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">static</span> <span style="color:Blue;">void</span>  Main()
{
    <span style="color:Blue;">using</span> (ApplicationLogger.Go(AppDomain.CurrentDomain))
    {
        <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> Exception(<span style="color:#A31515;">&quot;Hello!&quot;</span>);
    }
}

<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> ApplicationLogger : MarshalByRefObject
{
    ConcurrentQueue&lt;Exception&gt; queue = <span style="color:Blue;">new</span> ConcurrentQueue&lt;Exception&gt;();
    CancellationTokenSource cancellation;
    ManualResetEvent @<span style="color:Blue;">event</span>;

    <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> LogFCE(Exception message)
    {
        queue.Enqueue(message);
    }

    <span style="color:Blue;">private</span> <span style="color:Blue;">void</span> StartThread()
    {
        cancellation = <span style="color:Blue;">new</span> CancellationTokenSource();
        @<span style="color:Blue;">event</span> = <span style="color:Blue;">new</span> ManualResetEvent(<span style="color:Blue;">false</span>);
        <span style="color:Blue;">var</span> thread = <span style="color:Blue;">new</span> Thread(() =&gt;
        {
            <span style="color:Blue;">while</span> (!cancellation.IsCancellationRequested)
            {
                <span style="color:Blue;">if</span> (queue.TryDequeue(<span style="color:Blue;">out</span> <span style="color:Blue;">var</span> exception))
                {
                    Console.WriteLine(exception.Message);
                }
                Thread.Yield();
            }
            @<span style="color:Blue;">event</span>.Set();
        });
        thread.Start();
    }

    <span style="color:Blue;">private</span> <span style="color:Blue;">void</span> StopAndWait()
    {
        cancellation.Cancel();
        @<span style="color:Blue;">event</span>.WaitOne();
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">static</span> IDisposable Go(AppDomain observable)
    {
        <span style="color:Blue;">var</span> dom = AppDomain.CreateDomain(<span style="color:#A31515;">&quot;ApplicationLogger&quot;</span>, <span style="color:Blue;">null</span>, <span style="color:Blue;">new</span> AppDomainSetup
        {
            ApplicationBase = AppDomain.CurrentDomain.BaseDirectory,
        });

        <span style="color:Blue;">var</span> proxy = (ApplicationLogger)dom.CreateInstanceAndUnwrap(<span style="color:Blue;">typeof</span>(ApplicationLogger).Assembly.FullName, <span style="color:Blue;">typeof</span>(ApplicationLogger).FullName);

        proxy.StartThread();

        <span style="color:Blue;">var</span> subscription = <span style="color:Blue;">new</span> EventHandler&lt;FirstChanceExceptionEventArgs&gt;((_, args) =&gt;
        {
            proxy.LogFCE(args.Exception);
        });
        observable.FirstChanceException += subscription;

        <span style="color:Blue;">return</span> <span style="color:Blue;">new</span> Subscription(() =&gt; {
            observable.FirstChanceException -= subscription;
            proxy.StopAndWait();
        });
    }

    <span style="color:Blue;">private</span> <span style="color:Blue;">class</span> Subscription : IDisposable
    {
        Action act;
        <span style="color:Blue;">public</span> Subscription (Action act) {
            <span style="color:Blue;">this</span>.act = act;
        }

        <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> Dispose()
        {
            act();
        }
    }
}
</pre></div>
</div>
<p>In this case, the handling of <code>FirstChanceException</code> is done safely in an adjacent thread that belongs to a neighboring domain. Thus, the errors of message handling can’t bring worker threads down. Additionally, we can listen to <code>UnhandledException</code> in message logging domain: fatal errors during logging won’t bring the whole application down.</p>
<h3 id="appdomain.unhandledexception">AppDomain.UnhandledException</h3>
<p>The second message which we can catch and which refers to exception handling is <code>AppDomain.UnhandledException</code>. This message is bad news for us as it means that nobody was able to handle an error in some thread. It also means, that the only thing we can do is to clean up the consequences of such an error,  i.e. the resources assigned to this thread if they were created. However, it’s better to handle exceptions within threads, without bringing a thread down,  that means to use <code>try-catch</code>. Let’s check the efficiency of this approach.</p>
<p>Assume that we have a library that should create threads and implement some logic in them. We, as users of this library, are interested only in guaranteed API calls and getting error messages.</p>
<p>If the library brings down threads quietly, it won’t be of much use for us. Moreover, bringing down a thread will lead to an <code>AppDomain.UnhandledException</code> message which doesn’t indicates the affected thread. In case of our own code, this thread won’t be helpful either. Anyway, I haven’t seen situations where it could be necessary. Our task is to handle errors properly, log them, and terminate a thread correctly. In fact it means that we should wrap a method that starts a thread in <code>try-catch</code>:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
    ThreadPool.QueueUserWorkitem(_ =&gt; {
        <span style="color:Blue;">using</span>(Disposables aggregator = ...){
            <span style="color:Blue;">try</span> {
                <span style="color:Green;">// do work here, plus:</span>
                aggregator.Add(subscriptions);
                aggregator.Add(dependantResources);
            } <span style="color:Blue;">catch</span> (Exception ex)
            {
                logger.Error(ex, <span style="color:#A31515;">&quot;Unhandled exception&quot;</span>);
            }
        }
    });
</pre></div>
</div>
<p>With this scheme we will meet our goal: on the one hand, we don’t bring a thread down, on the other hand, we clean up local resources correctly if they were created. Also, we log those errors that we get.</p>
<p>&quot;<em>Hold on</em>&quot; - you might say - &quot;<em>You left the topic of</em> <code>AppDomain.UnhandledException</code> <em>event too quickly. Is it really unnecessary?</em>&quot;</p>
<p>Well, it is necessary. But we need it only to alert us if we forgot to wrap some threads in <code>try-catch</code> with all the necessary logic, including logging and resource cleanup. Otherwise, it would be completely wrong to address all exceptions as if they never occured.</p>

</div>
</div>
</body>
</html>